== Word-sized index into a byte (8-bit) array

Mnemonic::
add.uw _rd_, _rIndex_, _rBase_

Encoding::
[wavedrom]
....
{reg:[
    { bits:  7, name: 0x3b, attr: ['OP-32'] },
    { bits:  5, name: 'rd' },
    { bits:  3, name: 0x0, attr: ['ADD.UW'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 'rs2' },
    { bits:  7, name: 0x04 },
]}
....

Description::
Indexes into a byte (8-bit) array using a word-sized index by
zero-extended the word-sized index _rs1_ and adding the base _rs2_,
placing the result into _rd_.

Operation::
[source,sail]
--
let base = X(rs2);
let index = EXTZ(X(rs1)[31..0];

X(rd) = base + index;
--

Constrained unpredictable behaviour and reserved encodings::
 * If _rIndex_ is the zero-register (register 0), the result is
   constrained unpredicatable: it may cause the register _rd_ to be
   overwritten with the result of another operation encoded in the
   same opcode space or may cause an illegal instruction exception (if
   no other instruction is encoded into this opcode space).
 * Encodings where _rIndex_ is 0 (i.e. a total of 32
   code-points) are reserved for future use.

Pseudo-instructions::
zext.w _rd_, _rs_ is an alias for add.uw _rd_, _rs_, zero

