== Index into a word (32-bit) array

Mnemonic::
sh2add _rd_, _rIndex_, _rBase_

Encoding::
[wavedrom]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: 'rd' },
    { bits:  3, name: 0x4, attr: ['SH2ADD'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 'rs2' },
    { bits:  7, name: 0x10 },
]}
....

Description::
Indexes into a word (32-bit) array by shifting the index _rs1_ by
2 (multiplying with the size of a word-sized element) and adding
the base _rs2_, placing the result into _rd_.

Operation::
[source,sail]
--
let base = X(rs2);
let index = X(rs1);

X(rd) = base + (index << 2);
--

Constrained unpredictable behaviour and reserved encodings::
 * If _rIndex_ (_rs1_) or _rBase_ (_rs2_) are the zero-register
   (register 0), the result is constrained unpredicatable: it may
   cause the register _rd_ to be overwritten with the result of
   another operation encoded in the same opcode space or may cause an
   illegal instruction exception (if no other instruction is encoded
   into this opcode space).
 * Encodings where _rIndex_ or _rBase_ are 0 (i.e. a total of 63
   code-points) are reserved for future use.
