all:
	./bitmanip.sh

clean:
	- rm -f texput.log
	- rm -f bextcref-printperm.exe
	- rm -f bextcref-printperm.dat
	- rm -f bitmanip.aux
	- rm -f bitmanip.bbl
	- rm -f bitmanip.blg
	- rm -f bitmanip.log
	- rm -f bitmanip.out
	- rm -f bitmanip.pdf
	- rm -f bitmanip.toc
	- rm -f bextcref-*.tex
	- rm -f bextcref-*.dat
	- rm -f bextcref-*.exe
