=== Sign- and zero-extension

These instructions perform the sign-extension or zero-extension of the least
significant 8 bits, 16bits or 32 bits of the source register.

[%header,cols="^1,^1,4,8"]
|===
|RV32
|RV64
|Mnemonic
|Instruction

|&#10003;
|&#10003;
|sext.b _rd_, _rs_
|<<#insn-sext_b>>

|&#10003;
|&#10003;
|sext.h _rd_, _rs_
|<<#insn-sext_h>>

|
|&#10003;
|sext.w _rd_, _rs_
|addiw _rd_, _rs_, 0 (pseudo-instruction)

|&#10003;
|&#10003;
|zext.b _rd_, _rs_
|andi _rd_, _rs_, 255 (pseudo-instruction)

|&#10003;
|&#10003;
|zext.h _rd_, _rs_
|xref:insns/zext_h.adoc[Zero-extend a 16-bit quantity]

|
|&#10003;
|zext.w _rd_, _rs_
|xref:insns/zext_w.adoc[Zero-extend a 32-bit quantity]
|===

.Software Hint
[NOTE, caption="SW" ]
===============================================================
These instructions replace the generalised idioms `slli
rD,rS,(XLEN-<size>) + srli` (for zero-extension) or `slli + srai` (for
sign-extension) for the sign-extension of 8 bit and 16-bit quantities,
and for the zero-extension off 16 bit and 32 bit quantities.

The idiomatic forms for sign- and zero-extension on RISC-V use a
shift-left followed by either a shift-right-logical or a
shift-right-arithmetic; these can be used to extend values at any
bit-boundary required.
===============================================================
