= Zba sub-extension

[NOTE,caption=Frozen]
====
The Zba sub-extension is frozen.
====

The following instructions comprize the Zba sub-extension:

[%header,cols="^1,^1,4,8"]
|===
|RV32
|RV64
|Mnemonic
|Instruction

|
|&#10003;
|add.uw _rd_, _rs1_, _rs2_
|xref:insns/add_uw.adoc[add unsigned-word]
|&#10003;
|
|
|

|&#10003;
|&#10003;
|sh1add _rd_, _rs1_, _rs2_
|xref:insns/sh1add.adoc[Shift left by 1 and add]

|
|&#10003;
|sh1add.uw _rd_, _rs1_, _rs2_
|xref:insns/sh1add_uw.adoc[Shift unsigned word left by 1 and add]

|&#10003;
|&#10003;
|sh2add _rd_, _rs1_, _rs2_
|xref:insns/sh2add.adoc[Shift left by 2 and add]

|
|&#10003;
|sh2add.uw _rd_, _rs1_, _rs2_
|xref:insns/sh2add_uw.adoc[Shift unsigned word left by 2 and add]

|&#10003;
|&#10003;
|sh3add _rd_, _rs2_, _rs2_
|xref:insns/sh3add.adoc[Shift left by 3 and add]

|
|&#10003;
|sh3add.uw _rd_, _rs1_, _rs2_
|xref:insns/sh3add_uw.adoc[Shift unsigned word left by 3 and add]

|
|&#10003;
|slli.uw _rd_, _rs1_, _imm_
|xref:insns/slli_uw.adoc[Shift unsigned word left by immediate]

|===

.Software Hint
[NOTE, caption="SW" ]
===============================================================
The Zba instructins can be used to accelerate the generation of
addresses that index into arrays of basic types (halfword, word,
doubleword) using both unsigned word-sized and XLEN-sized indices: a
shifted index is added to a base address.

While the shift and add instructions are limited to a maximum left shift of
3, the slli instruction (from the base ISA) can be used to perform similar
shifts for indexing into arrays of wider elements. The slli.uw -- added in
this sub extension -- can be used when the index is to be interpreted as an
unsigned word.
===============================================================

.Architecture Explanation
[NOTE, caption="A" ]
===============================================================
We limited the shift and add instructions to a left shift of 1, 2, or 3
because these are commonly found in real-world code and bacause they
can be implemented with a minimal amount of additional hardware beyond
that of the simple adder. Our goal was to avoid lengthing the critical
path in implementations.
===============================================================

