= Zba sub-extension

[NOTE,caption=Frozen]
====
The Zba sub-extension is frozen.
====

[%header,cols="^1,^1,4,8"]
|===
|RV32
|RV64
|Mnemonic
|Instruction

|
|&#10003;
|add.uw _rd_, _rs1_, _rs2_
|xref:insns/add_uw.adoc[add unsigned word]

|&#10003;
|&#10003;
|sh1add _rd_, _rs1_, _rs2_
|xref:insns/sh1add.adoc[Shift left by 1 and add]

|
|&#10003;
|sh1add.uw _rd_, _rs1_, _rs2_
|xref:insns/sh1add_uw.adoc[Shift unsigned word left by 1 and add]

|&#10003;
|&#10003;
|sh2add _rd_, _rs1_, _rs2_
|xref:insns/sh2add.adoc[Shift left by 2 and add]

|
|&#10003;
|sh2add.uw _rd_, _rs1_, _rs2_
|xref:insns/sh2add_uw.adoc[Shift unsigned word left by 2 and add]

|&#10003;
|&#10003;
|sh3add _rd_, _rs2_, _rs2_
|xref:insns/sh3add.adoc[Shift left by 3 and add]

|
|&#10003;
|sh3add.uw _rd_, _rs1_, _rs2_
|xref:insns/sh3add_uw.adoc[Shift unsigned word left by 3 and add]

|
|&#10003;
|slli.uw _rd_, _rs1_, _imm_
|xref:insns/slli_uw.adoc[Shift unsigned word left by immediate]

|===

Architecture Comment::
We limited the shift and add instructions to a left shift of 1, 2, or 3
because these are commonly found in real-world code and bacause they
can be implemented with a minimal amount of additional hardware beyond
that of the simple adder. Our goal was to avoid lengthing the critical
path in implementations.

Software Hint::
The Zba instructins can be used to accelerate the generations of address
into arrays of basic types (halfword, word, doubleword) using both word-sized
and XLEN-sized indices: a shifted index is added to a base address.

Indexing into larger arrays using unsigned word pointers can be efficiently
performed using the slli.uw instruction

With word-sized indices on systems with XLEN larger than 32 bits, a
prefix zero-extension on the word-sized index is performed prior to
shifting the index.

Question::
Do we want to do anything about this - or just allow the duplication?
ALERT: The `shXadd` functions with either `zero` either for the index
or a base register shadows instructions from the base instruction set
or this extension (a base of zero is equivalent to a `slli` or
`slli.uw`; an index of zero is equivalent to an `addi rD,rBase,0`).
