[#insns-zip,reftext="Bit interleave"]
=== zip

Synopsis::
Gather odd and even bits of the source word into upper/lower halves of the
destination.

Mnemonic::
zip _rd_, _rs_

Encoding::
[wavedrom, , svg]
....
{reg:[
{bits: 2, name: 0x3},
{bits: 5, name: 0x4},
{bits: 5, name: 'rd'},
{bits: 3, name: 0x1},
{bits: 5, name: 'rs1'},
{bits: 5, name: 0x1e},
{bits: 7, name: 0x4},
]}
....

Description:: 
This instruction gathers all of the odd and even bits of a source word into
the high and low halves of a destination word.
It is the inverse of the <<insns-unzip,unzip>> instruction.
This instruction is available only on RV32.

Operation::
[source,sail]
--
val shfl_stage : (xlenbits, xlenbits, xlenbits, bits(4)) -> xlenbits
function shfl_stage (src, mL, mR, N) = {
    x : xlenbits = src & ~(mL | mR);
    y : xlenbits = ((src << N) & mL);
    z : xlenbits = ((src >> N) & mR);
    x | y | z
}

function clause execute ( ZIP (rs1,rd)) = {
    x : xlenbits = X(rs1);
    x = shfl_stage(x, 0x00ff0000, 0x0000ff00, 0x8);
    x = shfl_stage(x, 0x0f00f000, 0x000f00f0, 0x4);
    x = shfl_stage(x, 0x30303030, 0x0c0c0c0c, 0x2);
    x = shfl_stage(x, 0x44444444, 0x22222222, 0x1);
    X(rd) = x;
    RETIRE_SUCCESS
}
--

.Software Hint
[NOTE, caption="SH" ]
===============================================================
This instruction is useful for implementing the SHA3 cryptographic
hash function on a 32-bit architecture, as it implements the
bit-interleaving operation used to speed up the 64-bit rotations
directly.
===============================================================

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

|Zbkb (<<#zbkb>>)
|0.93
|Frozen
|===

